CREATE TABLE `main_data_center`.`mdc_user` (
  `ID` BIGINT(20) NOT NULL,
  `REAl_NAME` VARCHAR(50) NULL COMMENT '姓名',
  `SEX` CHAR(1) NULL COMMENT '性别',
  `BIRTHDAY` DATE NULL COMMENT '出生日期',
  `TELEPHONE` VARCHAR(15) NULL COMMENT '电话号码',
  `EMAIL` VARCHAR(50) NULL COMMENT '邮箱地址',
  `QQ` VARCHAR(15) NULL COMMENT 'QQ',
  `WX` VARCHAR(50) NULL COMMENT '微信',
  `WEI_BO` VARCHAR(50) NULL COMMENT '微博',
  `PHOTO` VARCHAR(50) NULL COMMENT '头像地址',
  `LEVEL_ID` BIGINT(20) NULL COMMENT '等级',
  `STATUS` CHAR(1) NULL COMMENT '状态',
  `CREATOR` BIGINT(20) NULL COMMENT '创建人',
  `CREATED` DATETIME NULL COMMENT '创建时间',
  `MODIFIER` BIGINT(20) NULL COMMENT '最后一次修改人',
  `MODIFIED` DATETIME NULL COMMENT '最后一次修改时间',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '主数据-人员信息表';
